# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uni_data.Campus')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
    ]
